version: '3'

services:
  flask_app:
    container_name: fun_english_server
    networks:
      - nginx_network
    restart: always
    build: ./
    volumes:
      - ./logs:/usr/src/flask_app/logs
    ports:
      - "16980:8000"
    command: gunicorn -c ./gunicorn.conf.py 'app:create_app()'
    
networks:
  nginx_network:
    external: true    
